<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:url"                content="http://www.pixeledpaper.com/ophoto" />
    <meta property="og:type"               content="website" />
    <meta property="og:title"              content="O Photo | Photography Studio" />
    <meta property="og:description"        content="Weddings, engagements, and more..." />
    <meta property="og:image"              content="http://www.pixeledpaper.com/ophoto/img/services.png" />

    <title>o photo | photography studio</title>

    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/app.css" />
    <link rel="stylesheet" href="css/styles.css" />
    <link rel="stylesheet" href="css/animate.css" />
    <link rel="stylesheet" href="css/default-skin.css">
    <link rel="stylesheet" href="css/photoswipe.css">
</head>