<div class="manage-nav">
    <h5>What would you like to do today?</h5>
    <ul>
        <li><a href="addcollection.php" id="add-collection" class="admin-link wow">ADD COLLECTION</a></li>
        <li><a href="addphotos.php" id="add-photos" class="admin-link wow">ADD PHOTOS TO COLLECTION</a></li>
        <li><a href="viewusers.php" id="view-clients" class="admin-link wow">VIEW CLIENTS</a></li>
        <li><a href="adduser.php" id="add-clients" class="admin-link wow">ADD CLIENT</a></li>
        <li><a href="myprofile.php" class="admin-link wow">UPDATE MY PROFILE</a></li>
        <li><a href="password.php" class="admin-link wow">CHANGE PASSWORD</a></li>
    </ul>
</div>