<div class="manage-nav">
    <h5>What would you like to do today?</h5>
    <ul>
        <li><a href="mycollections.php" id="my-collection" class="admin-link wow">VIEW COLLECTIONS</a></li>
        <li><a href="myprofile.php" id="view-clients" class="admin-link wow">MANAGE PROFILE</a></li>
        <li><a href="password.php" id="change-password" class="admin-link wow">CHANGE PASSWORD</a></li>
    </ul>
</div>